apiVersion: apps/v1
kind: Deployment
metadata:
        name: mongo-service
        labels:
              app: mongo-service
spec:
     replicas: 1
     selector:
             matchLabels:
                        app: mongo-service
     template:
              metadata:
                      labels:
                         app: mongo-service
              spec:
                      containers:
                              - name: mongo-service
                                image: docker.io/michealbmullin/projmongo
                                ports:
                                        - containerPort: 3000
