apiVersion: v1
kind: Service
metatdata:
         name:
             app: mongo-service
spec:
    selector:
            app: mongo-service
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
    type: ClusterIP
