apiVersion: apps/v1
kind: Deployment
metadata:
        name: secret-deployment
        labels:
              app: secret-deployment
spec:
    selector:
            app: secret-deployment
    template:
            metadata:
                    labels:
                          app: secret-deployment
    spec:
        containers:
                - name: secret-deployment
                  image: michealbmullino/projsec
                  ports:
                     - containerPort:3000
