apiVersion: v1
kind: Service
metadata:
         name:
             app: session-token-service
spec:
    selector:
            app: session-token-service
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
    type: ClusterIP
