apiVersion: v1
kind: Service
metatdata:
         name:
             app: account-service
spec:
    selector:
            app: account-service
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
    type: ClusterIP
