apiVersion: apps/v1
kind: Deployment
metadata:
        name: authentication-service
        labels:
              app: authentication-service
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: authentication-service
        template:
                metadata:
                        labels:
                              app: authentication-service
                spec:
                        containers:
                            - name: authentication-service
                              image: michealbmullin/projauthenserv
                              envFrom:
                                      - secretRef:
                                              name: devop-secrets
                              ports:
                                     - containerPort: 3000
