apiVersion: apps/v1
kind: Deployment
metadata:
        name: role-service
        labels:
              app: role-service
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: role-service
        template:
                metadata:
                        labels:
                              app: role-service
                spec:
                        containers:
                                - name: role-service
                                  image: michealbmullin/projroleserv
                                  ports:
                                        - containerPort: 3000
