apiVersion: apps/v1
kind: Deployment
metadata:
        name: group-deployment
        labels:
              app: group-deployment
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: group-deployment
        template:
                metadata:
                        labels:
                              app: group-deployment
                spec:
                        containers:
                            - name: group-deployment
                              image: michealbmullin/projgroupserv
                              ports:
                                    - containerPort: 3000
