apiVersion: apps/v1
kind: Deployment
metadata:
        name: gateway
        labels:
              app: gateway
spec:
    selector:
            app: gateway
    template:
            metadata:
                    labels:
                          app: gateway
    spec:
        containers:
                - name: gateway
                  image: michealbmullin/projgateway
                  ports:
                     - containerPort:80
